# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)

1.18.4


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [6]:
memory_size = null_vector.size * null_vector.itemsize
print(f'Memory size of array = {memory_size} bytes')

Memory size of array = 80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

### Solution 1

In [8]:
new_vector = np.zeros(10)
new_vector[4] = 1
new_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### Solution 2

In [25]:
(np.arange(10) == 4) * 1

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

### Solution 3

In [33]:
(np.arange(10)== 4).view(np.uint8)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=uint8)

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
vector = np.arange(10, 50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

 #### Solution 1

In [39]:
np.flipud(np.arange(10))

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### Solution 2

In [37]:
np.arange(10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [41]:
arr = np.arange(9)
arr.reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [47]:
arr = np.array([1,2,0,0,4,0])
non_zeros = arr[arr != 0]
non_zeros

array([1, 2, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [48]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [11]:
np.random.rand(3,3,3)

array([[[0.08892621, 0.18652524, 0.07452329],
        [0.31515725, 0.07945931, 0.60822251],
        [0.43307691, 0.74926215, 0.57474853]],

       [[0.76058539, 0.29638111, 0.97877988],
        [0.50950921, 0.47725625, 0.37955188],
        [0.38267085, 0.00687459, 0.57721231]],

       [[0.51369193, 0.11592252, 0.45970579],
        [0.81788457, 0.2038097 , 0.3108716 ],
        [0.25710102, 0.21737803, 0.68102654]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
min_value  = np.random.rand(10,10).min()
min_value

0.009708504058176581

In [14]:
max_value = np.random.rand(10,10).max()
max_value

0.9950614034102329

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [56]:
np.random.rand(30).mean()

0.5108713982071814

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
arr = np.ones((5,5))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [23]:
arr = np.random.randint(5, size=(5,5))
np.pad(arr, pad_width=1, constant_values=0)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 3, 1, 1, 0],
       [0, 3, 4, 1, 0, 0, 0],
       [0, 3, 3, 2, 0, 0, 0],
       [0, 1, 4, 0, 3, 0, 0],
       [0, 0, 2, 4, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan               nan
np.nan == np.nan         False
np.inf > np.nan          False
np.nan - np.nan          False
np.nan in set([np.nan])  True
0.3 == 3 * 0.1           False
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [99]:
np.diagflat([1,2,3,4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [117]:
np.indices((8,8)).sum(axis=0) % 2

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [143]:
arr = np.random.rand(6*7*8).reshape(6,7,8)
#np.where(arr = 100)
hundreth_element = arr.flat[100]

x,y,z = np.where(arr == hundreth_element)


In [144]:
index_hundred = 0
for idx, val in np.ndenumerate(arr):
    if val == hundreth_element:
        index_hundred = idx

In [145]:
index_hundred

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [152]:
arr = np.arange(4)
np.tile(arr, (2,2))

array([[0, 1, 2, 3, 0, 1, 2, 3],
       [0, 1, 2, 3, 0, 1, 2, 3]])

In [181]:
np.tile(np.array([[0,1], [0,1]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [24]:
a = np.random.randint(3, size=(4,4))
amax, amin = a.max(), a.min()
a = (a-amin)/(amax - amin)
a

array([[0.5, 0.5, 0.5, 0.5],
       [0. , 1. , 0.5, 0. ],
       [1. , 0.5, 0. , 0. ],
       [1. , 0. , 0.5, 1. ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [188]:
color = np.dtype([("r", np.ubyte), # dtype structured data type
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [204]:
np.array([12,123,45, 79], dtype = color)

array([( 12,  12,  12,  12), (123, 123, 123, 123), ( 45,  45,  45,  45),
       ( 79,  79,  79,  79)],
      dtype=[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [207]:
np.random.rand(4)

array([0.06607007, 0.24334542, 0.59908037, 0.55618831])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [208]:
a = np.arange(15).reshape(5,3)
b = np.random.rand(3,2)
np.dot(a,b)

array([[ 0.57015657,  1.34427071],
       [ 2.48102048,  6.85490311],
       [ 4.3918844 , 12.3655355 ],
       [ 6.30274832, 17.8761679 ],
       [ 8.21361224, 23.38680029]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [29]:
arr = np.arange(10)
arr[3:8] *= -1
arr

array([ 0,  1,  2, -3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))    >>>>>> 9
from numpy import *
print(sum(range(5),-1))     >>>>> 10
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)  >>>>>>>>> nan
np.array(0) // np.array(0) >>>>>>>>>  0
np.array([np.nan]).astype(int).astype(float)  >>>>>>>> array([-2.14748365e+09])
```

In [220]:
np.array(0) / np.array(0)

nan

In [217]:
np.array(0) // np.array(0)

0

In [218]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [225]:
arr = np.random.rand(10)
arr

array([0.3709484 , 0.64719247, 0.78603863, 0.6137108 , 0.11585435,
       0.93753594, 0.44752119, 0.76534933, 0.91976022, 0.41197541])

In [226]:
np.round(arr, decimals=1)

array([0.4, 0.6, 0.8, 0.6, 0.1, 0.9, 0.4, 0.8, 0.9, 0.4])

In [227]:
np.round_(arr, decimals=1)

array([0.4, 0.6, 0.8, 0.6, 0.1, 0.9, 0.4, 0.8, 0.9, 0.4])

In [228]:
np.around(arr, decimals=1)

array([0.4, 0.6, 0.8, 0.6, 0.1, 0.9, 0.4, 0.8, 0.9, 0.4])

#### 30. How to find common values between two arrays? (★☆☆)

In [229]:
arr1 = np.arange(1,20)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [235]:
arr2 = np.arange(10, 31)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [236]:
np.intersect1d(arr1, arr2)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [244]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [242]:
np.sqrt()

nan

In [241]:
np.emath.sqrt()

1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [245]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-12-06
Today:  2020-12-07
Tomorrow:  2020-12-08


In [52]:
np.timedelta64(1, 'D')

numpy.timedelta64(1,'D')

In [258]:
np.datetime64(today, 'D')

numpy.datetime64('2020-12-07')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [267]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
(A += B) * (A /= -2)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [54]:
arr = np.random.uniform(1,10,5)
arr

array([6.46634431, 1.28007864, 2.83896969, 2.30434825, 8.52644006])

In [55]:
arr.astype(int)

array([6, 1, 2, 2, 8])

In [56]:
arr - (arr % 1)

array([6., 1., 2., 2., 8.])

In [57]:
np.floor(arr)

array([6., 1., 2., 2., 8.])

In [58]:
np.trunc(arr)

array([6., 1., 2., 2., 8.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [274]:
arr = np.zeros((5,5))
arr += np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
