# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.19.3


#### 2. Print the numpy version and the configuration (★☆☆)

#### 3. Create a null vector of size 10 (★☆☆)

In [21]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [20]:
memory_size = null_vector.itemsize * null_vector.itemsize
print(f'Memory size of array = {memory_size} bytes')

Memory size of array = 64 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [22]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [23]:
new_vector = np.zeros(10)
new_vector[4] = 1
new_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [25]:
(np.arange(10) == 4) * 1

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [33]:
(np.arange(10)== 4).view(np.uint8)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=uint8)

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [35]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [39]:
np.flipud(np.arange(10))

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [37]:
np.arange(10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [41]:
arr = np.arange(9)
arr.reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [47]:
arr = np.array([1,2,0,0,4,0])
non_zeros = arr[arr != 0]
non_zeros

array([1, 2, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [48]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [49]:
np.random.rand(3,3,3)

array([[[0.97073081, 0.8095057 , 0.99864209],
        [0.21226063, 0.47719608, 0.43807272],
        [0.38348043, 0.66026124, 0.22696324]],

       [[0.75594971, 0.85503588, 0.4757874 ],
        [0.31043579, 0.65918464, 0.12137763],
        [0.52115346, 0.82156205, 0.03993468]],

       [[0.65369338, 0.35658513, 0.89763902],
        [0.96999556, 0.95925312, 0.53880184],
        [0.55674637, 0.78029986, 0.93394328]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [53]:
(np.random.rand(10,10)).min()

0.011746925023670474

In [54]:
(np.random.rand(10,10)).max()

0.9952732138923055

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [56]:
np.random.rand(30).mean()

0.5108713982071814

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [73]:
arr = np.ones((5,5))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [86]:
arr = np.random.randint(5, size=(5,5))
np.pad(arr, pad_width=1, constant_values=0)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 1, 2, 0],
       [0, 1, 3, 3, 2, 4, 0],
       [0, 0, 2, 1, 2, 1, 0],
       [0, 0, 2, 3, 1, 4, 0],
       [0, 3, 2, 2, 3, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan               nan
np.nan == np.nan         False
np.inf > np.nan          False
np.nan - np.nan          False
np.nan in set([np.nan])  True
0.3 == 3 * 0.1           False
```

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [99]:
np.diagflat([1,2,3,4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [117]:
np.indices((8,8)).sum(axis=0) % 2

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

In [159]:
def printcheckboard(n): 
      
    print("Checkerboard pattern:") 
  
    # create a n * n matrix 
    x = np.zeros((n, n), dtype = int) 
  
    # fill with 1 the alternate rows and columns 
    x[1::2, ::2] = 1
    x[::2, 1::2] = 1
      
    # print the pattern 
    for i in range(n): 
        for j in range(n): 
            print(x[i][j], end =" ")  
        print() 

In [160]:
printcheckboard(6)

Checkerboard pattern:
0 1 0 1 0 1 
1 0 1 0 1 0 
0 1 0 1 0 1 
1 0 1 0 1 0 
0 1 0 1 0 1 
1 0 1 0 1 0 


In [128]:
np.indices((4,4))#.sum(axis=1)

array([[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]])

In [132]:
np.indices((4,4)).sum(axis=0)

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [143]:
arr = np.random.rand(6*7*8).reshape(6,7,8)
#np.where(arr = 100)
hundreth_element = arr.flat[100]

x,y,z = np.where(arr == hundreth_element)


In [144]:
index_hundred = 0
for idx, val in np.ndenumerate(arr):
    if val == hundreth_element:
        index_hundred = idx

In [145]:
index_hundred

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [152]:
arr = np.arange(4)
np.tile(arr, (2,2))

array([[0, 1, 2, 3, 0, 1, 2, 3],
       [0, 1, 2, 3, 0, 1, 2, 3]])

In [181]:
np.tile(np.array([[0,1], [0,1]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [182]:
a = np.random.randint(3, size=(4,4))
amax, amin = a.max(), a.min()
a = (a-amin)/(amax - amin)
a

array([[0.5, 0. , 0. , 1. ],
       [0. , 1. , 0.5, 0.5],
       [1. , 0. , 0. , 0. ],
       [0. , 1. , 0. , 1. ]])

In [164]:
a = np.random.randint(3, size=(4,4))


array([[2, 2, 0, 1],
       [2, 0, 2, 0],
       [1, 2, 0, 0],
       [0, 2, 1, 0]])

In [168]:
a/np.linalg.norm(a, axis=1)

array([[0.66666667, 0.70710678, 0.        , 0.4472136 ],
       [0.66666667, 0.        , 0.89442719, 0.        ],
       [0.33333333, 0.70710678, 0.        , 0.        ],
       [0.        , 0.70710678, 0.4472136 , 0.        ]])

In [171]:
row_sums = a.sum(axis=1)

new_matrix = a / row_sums[:, np.newaxis]
new_matrix

array([[0.4       , 0.4       , 0.        , 0.2       ],
       [0.5       , 0.        , 0.5       , 0.        ],
       [0.33333333, 0.66666667, 0.        , 0.        ],
       [0.        , 0.66666667, 0.33333333, 0.        ]])

In [178]:
a / row_sums[:, np.newaxis]

array([[0.4       , 0.4       , 0.        , 0.2       ],
       [0.5       , 0.        , 0.5       , 0.        ],
       [0.33333333, 0.66666667, 0.        , 0.        ],
       [0.        , 0.66666667, 0.33333333, 0.        ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [188]:
color = np.dtype([("r", np.ubyte), # dtype structured data type
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [204]:
np.array([12,123,45, 79], dtype = color)

array([( 12,  12,  12,  12), (123, 123, 123, 123), ( 45,  45,  45,  45),
       ( 79,  79,  79,  79)],
      dtype=[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [207]:
np.random.rand(4)

array([0.06607007, 0.24334542, 0.59908037, 0.55618831])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [208]:
a = np.arange(15).reshape(5,3)
b = np.random.rand(3,2)
np.dot(a,b)

array([[ 0.57015657,  1.34427071],
       [ 2.48102048,  6.85490311],
       [ 4.3918844 , 12.3655355 ],
       [ 6.30274832, 17.8761679 ],
       [ 8.21361224, 23.38680029]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [209]:
arr = np.arange(10)
arr[3:8] *= -1
arr

array([ 0,  1,  2, -3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [214]:
print(sum(range(5), -1))
np.sum(range(5), -1)

10


10

In [215]:

print(sum(range(5), -1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [220]:
np.array(0) / np.array(0)

nan

In [217]:
np.array(0) // np.array(0)

0

In [218]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [225]:
arr = np.random.rand(10)
arr

array([0.3709484 , 0.64719247, 0.78603863, 0.6137108 , 0.11585435,
       0.93753594, 0.44752119, 0.76534933, 0.91976022, 0.41197541])

In [226]:
np.round(arr, decimals=1)

array([0.4, 0.6, 0.8, 0.6, 0.1, 0.9, 0.4, 0.8, 0.9, 0.4])

In [227]:
np.round_(arr, decimals=1)

array([0.4, 0.6, 0.8, 0.6, 0.1, 0.9, 0.4, 0.8, 0.9, 0.4])

In [228]:
np.around(arr, decimals=1)

array([0.4, 0.6, 0.8, 0.6, 0.1, 0.9, 0.4, 0.8, 0.9, 0.4])

#### 30. How to find common values between two arrays? (★☆☆)

In [229]:
arr1 = np.arange(1,20)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [235]:
arr2 = np.arange(10, 31)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [236]:
np.intersect1d(arr1, arr2)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [244]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [242]:
np.sqrt()

nan

In [241]:
np.emath.sqrt()

1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [245]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-12-06
Today:  2020-12-07
Tomorrow:  2020-12-08


In [250]:
np.timedelta64(1, 'D')

numpy.timedelta64(1,'D')

In [258]:
np.datetime64(today, 'D')

numpy.datetime64('2020-12-07')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [267]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
(A += B) * (A /= -2)

In [272]:
p =1
p += 7
p /= -2
p

-4.0

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [285]:
arr = np.random.uniform(1,10,5)
arr

array([7.87939138, 6.51752988, 9.24390039, 9.83850895, 9.49232331])

In [291]:
arr.astype(int)

array([7, 6, 9, 9, 9])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [274]:
arr = np.zeros((5,5))
arr += np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [101]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [100]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [6]:
v = np.random.random(10)

In [9]:
v

array([0.11519092, 0.82693576, 0.24120693, 0.54251056, 0.62007788,
       0.8786801 , 0.01354749, 0.55632817, 0.6358159 , 0.78034271])

In [10]:
v_sorted = np.sort(v)

In [11]:
v_sorted

array([0.01354749, 0.11519092, 0.24120693, 0.54251056, 0.55632817,
       0.62007788, 0.6358159 , 0.78034271, 0.82693576, 0.8786801 ])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [16]:
A = np.arange(10)
B = np.arange(5, 15)

In [18]:
B

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
%timeit A.sum()

2.15 µs ± 224 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [26]:
%timeit np.sum(A)

4.19 µs ± 235 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [27]:
%timeit B.sum()

2.06 µs ± 155 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [28]:
%timeit np.sum(B)

4.11 µs ± 532 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [29]:
A = np.arange(10)
B = np.arange(5, 15)

In [30]:
(A==B).all()

False

In [31]:
np.array_equal(A,B)

False

In [32]:
np.array_equal(A,A)

True

#### 43. Make an array immutable (read-only) (★★☆)

In [33]:
Z = np.arange(10)
Z.flags.writeable = False


In [35]:
Z[1] = 9

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [44]:
M = np.random.random((10,2))
M

array([[0.77645578, 0.64447756],
       [0.18414534, 0.01683161],
       [0.64701958, 0.51636713],
       [0.78991777, 0.04481812],
       [0.65635339, 0.77946927],
       [0.64645162, 0.68887858],
       [0.8353052 , 0.99008874],
       [0.92751482, 0.69927497],
       [0.46193235, 0.92629486],
       [0.67834611, 0.57170833]])

In [45]:
x,y = M[:,0], M[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[1.00907626 0.18491298 0.82780997 0.79118819 1.01900546 0.94469752
 1.29538044 1.16158048 1.03508631 0.88713238]
[0.69278252 0.09115066 0.67356321 0.05667694 0.87093482 0.81716011
 0.8699904  0.64600725 1.10819868 0.70029768]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [106]:
Z = np.random.random((10))

In [107]:
Z

array([0.30983657, 0.21284984, 0.58210144, 0.4175802 , 0.05697167,
       0.90642475, 0.35924506, 0.19787617, 0.57647613, 0.66231761])

In [111]:

#Z[np.where(Z == Z.max())]#= 0
Z[Z.argmax()] = 0

array([0.90642475])

In [112]:
Z

array([0.30983657, 0.21284984, 0.58210144, 0.4175802 , 0.05697167,
       0.        , 0.35924506, 0.19787617, 0.57647613, 0.66231761])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [102]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [73]:
x = np.random.random(5)
y= np.random.random(5)


cauchy_m = 1.0 / (x.reshape((-1,1)) - y)

In [74]:
cauchy_m

array([[ -3.76904193,   3.12153134,   8.23666806,  -3.55357505,
         -2.10974838],
       [ -1.52721733, -14.46954916,  -3.730537  ,  -1.49059512,
         -1.15813605],
       [ -1.90142401,  16.7354554 ,  -7.18422333,  -1.84498796,
         -1.36129917],
       [  7.94747738,   1.40547922,   1.95101462,   9.11255092,
        -12.07078281],
       [ -2.81798022,   4.33255092,  31.3837382 ,  -2.69577072,
         -1.77451314]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [71]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [78]:
#np.set_printoptions(threshold=np.nan)
Z = np.zeros((50,50))
print(Z)
np.set_printoptions()

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [99]:
np.set_printoptions(threshold=np.Infinity)
Z = np.zeros((50,50))
print(Z)
np.set_printoptions()

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [80]:
np.set_printoptions(threshold=10000)
Z = np.zeros((50,50))
print(Z)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [83]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()


In [82]:
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [84]:
v

95.42523201269825

In [94]:
print(Z[index])

95
